### ISSUE TITLE
4.3. 使用 MiniVM 调试

### ISSUE THREAD

**Issue by MaxXSoft** [pku-minic/online-doc#1]
https://pku-minic.github.io/online-doc/#/ir/minivm 

 北京大学编译实践课程在线文档

**Comment by PanJason** [comment]
hexadecimal-const的第一条规则后面的hexadecimal-digit是多余的吗？这样会让hexadecimal至少要两个数字？

**Comment by Philip-2000** [comment]
readline库装不明白呀！求助！
我是把他的源代码的git仓库从官网上下下来然后按照它的编译安装指导一步一步安装的。但是还是给我报出静态链接库中有未定义的引用。百度了一圈也没有结果，非常迷惑。
