### ISSUE TITLE
关于SysY文法中的ConstExp

### ISSUE THREAD

**Issue by victbr** [pku-minic/online-doc#2]
在文档中ConstExp和Exp的规则是一样的， 而这样得到的文法中需要使用常量表达式的地方可能输入的是一个带变量的表达式，（例如函数定义的参数等），请问这里的ConstExp会出现带变量的情况吗，还是可以在编译的时候就求出值。

**Comment by MaxXSoft** [comment]
文档 [3.1. 文法定义](https://pku-minic.github.io/online-doc/#/sysy/ebnf)一节曾提到:

> `ConstExp`: 其中使用的 `IDENT` 必须是常量.

所以你所问的问题中, 需要使用到常量表达式 (`ConstExp`) 的地方可能会出现如 `x + y` 的情况, 但此时, `x` 和 `y` (`IDENT`) 都必须是常量. 如果其中之一无法在编译时被确定为常量, 则该表达式非法, 编译器应当报错.

你实现的编译器应正确处理可能出现的编译错误.
