### ISSUE TITLE
请问Cond/LOrExp不算Exp是bug还是feature

### ISSUE THREAD

**Issue by victbr** [pku-minic/online-doc#3]
在SysY的文法定义里逻辑表达式不能归约到Exp，而根据关于逻辑表达式的定义，以下表达式是不属于SysY语言的
```c++
(a || b) && c
```

**Comment by MaxXSoft** [comment]
- SysY 语言的定义来自于编译系统设计赛组委会提供的技术规范.
- 本课程需要兼容上述技术规范, 除非万不得已, 不会自行维护一个与原版 SysY 有差异的分支版本.
- 这个行为和 C 语言不一致, 但并不影响功能.

综上所述, 是 feature.
