### ISSUE TITLE
项目非常棒，里面提到了 Rust

### ISSUE THREAD

**Issue by sunface** [pku-minic/online-doc#7]
> 我们不建议之前从未接触过 Rust, 对内存管理/所有权等概念不敏感, 且对自己编码水平没什么信心的同学使用 Rust 开发编译器. 对这些同学来说, 在编译实践中上手 Rust 可能会比较痛苦

这句话很认同，至少现有的 Rust 教程并没有解决从学习到上手实践的问题，但是有一个开源 Rust 教程： https://course.rs ，非常适合系统化的学习 Rust 语言。

如果您看了后觉得内容还不错的话，作者大大可以在编译器教程中推荐给想要使用 Rust 写编译器的同学：）

**Comment by MaxXSoft** [comment]
感谢您的关注和反馈!

写这段话的原因是: 在上学期的编译课程中, 我们就支持使用 Rust 写编译器了. 但最后我们发现, 有些同学被 Rust 的“名头”吸引, 决定用 Rust 写编译器, 结果险些翻车. 当然究其原因可能是我当时把 Rust 吹得太猛了🤦‍♂️, 我的锅, 不过我个人还是非常喜欢 Rust 的.

后来想想, 用什么编程语言写编译器, 包括写各种其他软件, 这件事并不重要. 没有最好用的语言, 只有最合适的语言. 我们提供 Rust 也只是作为一个可选项, 让那些愿意接受新事物的同学感受一下 Rust 的魅力. 之后我们也可能会加入对其他新语言的支持. 而现阶段, 在课程中, 我们只是建议同学们量力而行, 选择自己最擅长的编程语言来完成实践.

您写的教程之前早有耳闻, 也读过其中的部分章节, 学到了很多东西. 感谢您对 Rust 中文社区做出的贡献! 同为教程作者, 我能体会到您写这份教程时的不易. 如有机会, 我会向大家推荐这个教程的!

**Comment by sunface** [comment]
优秀的东西值得被推荐，我大概看了下内容，受益匪浅，后面会推荐给有需要的人，感谢付出，共勉 :)
