### ISSUE TITLE
Unable to access online documents because CDN is not accessible

### ISSUE THREAD

**Issue by v1nh1shungry** [pku-minic/online-doc#84]
I used to be able to access https://pku-minic.github.io/online-doc/, but recently I can't, and it looks like it's because I can't access the CDN, which is jsdelivr. By the way I can access Github and Google normally.

![image](https://user-images.githubusercontent.com/98312435/169467455-c6455cb3-2f8d-499d-bb72-2580f33d63a2.png)

Has anyone encountered the same situation as me? Or what can I do to solve this problem? Otherwise please consider using another CDN, or just copy `docsify` files to the docs path with `docsify init docs --local`.

**Comment by MaxXSoft** [comment]
We just switched the CDN to `npm.elemecdn.com`.

BTW, do you have any CDN recommendations?

**Comment by v1nh1shungry** [comment]
Thanks for replying! Now I can access the website!

> BTW, do you have any CDN recommendations?

Sorry, I have no idea about this.
