### ISSUE TITLE
常量数组作为函数实参的情况需补充说明

### ISSUE THREAD

**Issue by jokerwyt** [pku-minic/online-doc#89]
考虑如下sys-y代码：

```
int func(int a[]) {
  a[1] = 2;
}

int main() {
  const int a[3] = {0,0,0};
  int b[3] = {0, 0, 0};
  func(a);
  func(b);
}
```

`func(b)`应该是合法行为，但是`func(a)`不是。因为根据文档说明，const是编译期求值+不允许修改。
是否应该明确禁止常量数组（以及其部分解引用）作为函数实参？

**Comment by jokerwyt** [comment]
![image](https://github.com/pku-minic/online-doc/assets/11886705/1f60eb8a-85cb-4601-8fe3-73a9cb30ca4c)
另一个问题：clang和gcc对初始化列表的要求似乎不尽相同，`int a[2][2] = {1, {}}`这种声明在Sys-Y中应该是不合法的，在gcc中也会有警告。但在（至少图中版本）的clang是没有警告的。

**Comment by MaxXSoft** [comment]
> `func(b)`应该是合法行为，但是`func(a)`不是。因为根据文档说明，const是编译期求值+不允许修改。

没错，原则上是这样的。

> 是否应该明确禁止常量数组（以及其部分解引用）作为函数实参？

我觉得应该加上这样的限制，同时据我所知目前的测试用例应该没有这种行为。

感谢建议！

**Comment by MaxXSoft** [comment]
> clang和gcc对初始化列表的要求似乎不尽相同，`int a[2][2] = {1, {}}`这种声明在Sys-Y中应该是不合法的，在gcc中也会有警告。但在（至少图中版本）的clang是没有警告的。

确实如此。这里的本意只是引入多维数组，顺便配合一下编译设计赛介绍多维数组初始化。

但坏就坏在 C 语言这个初始化语法实在是太复杂了，不加限制的话很难写出一个在所有情况下都符合人类直觉的实现。更何况如你所说，编译器和编译器之间也有差异——事实上，对于 C/C++ 编译器而言，尤其后者，这种事情实在是太常见了，我能轻松举出十个这种例子。这也是我不建议初学者上来就接触 C/C++ 里过于拗口的语言细节的原因，它除了把你培养成一个语言律师以外，基本没什么好处。

因此，出于教学考虑，我觉得在未来应该进一步降低多维数组初始化语法的复杂度，加更多限制。

感谢建议。

**Comment by MaxXSoft** [comment]
> 另一个另一个问题，有关Koopa IR规范。如下程序使用example/interpreter来跑，会报错：
> 
> ```
> global @i32_arr = alloc [[i32, 5], 3], {zeroinit, {1, 2, 3, 4, 5}, {1999, 0, 0, 0, 0}}
> 
> fun @main(): i32 {
> %entry:
>   %14 = getelemptr @i32_arr, 1  // *[i32, 5]
>   %15 = getelemptr %14, 0       // *i32
>   %ptr = getptr %15, 4          // *i32, it's valid.
>   %ptr2 = getptr %15, 5         // error. The interpreter said "pointer calculation out of bounds with index 0 and length 5"
>   %ret = load %ptr
>   ret %ret
> }
> ```
> 
> %ptr2企图得到一个指向数组中1999的*i32指针，但是失败了。 原因似乎是，getptr并不支持无限制寻址。docs应该没有提到这一点。

需要申明的一点是：`example` 目录的实现并不作为标准实现，这些例子存在的目的只是展示 Koopa 框架的可用性。

在实现上，我当时写这个例子的时候确实忽略了这个问题。主要是你在写 Rust 的时候，主观上会避免这种危险情况出现，即便你已经用了 `unsafe` 让 `rustc` 闭嘴了。

但你编译器后端的实现是自由的，标准没有禁止这种写法，虽然看起来很怪，但可以这样做。

**Comment by jokerwyt** [comment]
好的，感谢
